### ISSUE TITLE
Monthly Payment total

### ISSUE THREAD

**Issue by collinskoech11** [collinskoech11/AssetManagement#2]
Calculate total payment for individual months to render as bar chart using chart js at Revenue.html

**Comment by collinskoech11** [comment]
current bar chart statically designed

**Comment by paulonteri** [comment]
Hi, sorry, why the mention?

**Comment by collinskoech11** [comment]
needed clarification on whether to use chart js or matplotlib for the
monthly revenue graphs.
Decid3ed to go with matplotlib & pandas
